"""Add tumanasi tables

Revision ID: c76d836672f6
Revises: convert_enums_to_varchar
Create Date: 2026-02-23 16:23:41.283628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c76d836672f6'
down_revision: Union[str, None] = 'convert_enums_to_varchar'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'deliverables', 'bids', ['bid_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'deliverables', 'influencer_profiles', ['influencer_id'], ['id'], ondelete='CASCADE')
    op.alter_column('orders', 'digital_download_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('products', 'is_digital',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'is_digital',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('orders', 'digital_download_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'deliverables', type_='foreignkey')
    op.drop_constraint(None, 'deliverables', type_='foreignkey')
    # ### end Alembic commands ###
