"""Add tumanasi_expenses and tumanasi_rider_payments tables

Revision ID: 8d07a6f8d632
Revises: fix_all_enum_types_2026
Create Date: 2026-04-16 14:32:24.849256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d07a6f8d632'
down_revision: Union[str, None] = 'fix_all_enum_types_2026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('product', 'brand', name='categorytype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_categories_slug'), 'system_categories', ['slug'], unique=True)
    op.create_table('tumanasi_expenses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('expense_date', sa.DateTime(), nullable=False),
    sa.Column('category', sa.Enum('fuel', 'maintenance', 'marketing', 'office_supplies', 'utilities', 'insurance', 'equipment', 'rent', 'salaries', 'other', name='expensecategorydb'), nullable=False),
    sa.Column('amount_kes', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tumanasi_rider_payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rider_id', sa.String(length=36), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('payment_period_start', sa.DateTime(), nullable=False),
    sa.Column('payment_period_end', sa.DateTime(), nullable=False),
    sa.Column('deliveries_completed', sa.Integer(), nullable=True),
    sa.Column('total_earnings_kes', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deductions_kes', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('net_payment_kes', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'mpesa', 'bank_transfer', 'cheque', name='riderpaymentmethoddb'), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('paid_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['paid_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rider_id'], ['tumanasi_riders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tumanasi_rider_payments')
    op.drop_table('tumanasi_expenses')
    op.drop_index(op.f('ix_system_categories_slug'), table_name='system_categories')
    op.drop_table('system_categories')
    # ### end Alembic commands ###
